### ISSUE TITLE
What is this based on?

### ISSUE THREAD

**Issue by Bialogs** [mitre/nginx-stigready-baseline#12]
@aaronlippold Do you remember what this profile is based on? I realize it maps back to the Web SRG, but where did all the check and fix text come from?

**Comment by aaronlippold** [comment]
I belive that Nhi based this on the actual Web SRG and created the baseline. This is the correct formal process for creating what DISA agreed we can call 'STIG Ready Content'.  This is the correct method for any vender creating content from SRGs and the process that would happen if you were working with DISA on an approved STIG development project.

The check and fix text would have come from refactoring the general check and fix text from the SRG and rewording it to be specific to NGINX. If I recall, I also suggested Nhi review the wording from other web stigs (apache) and the cross-walk baseline that @ejaronne and @aaronlippold did for the other nginx-baseline project.
