### ISSUE TITLE
Setup a github action to run the profile on push to master, releases and branches

### ISSUE THREAD

**Issue by aaronlippold** [mitre/nginx-stigready-baseline#3]
This can be used as a reference - however, you can do it locally to GH Actions as we can easily pull down the container and perhaps just install Nginx on the running actions box, etc.

https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/v2.6/.github/workflows/greetings_program.yml

This is the general workflow and we could do a `matrix` between the container and VM test case

**Comment by ntruong18** [comment]
Github Actions created for testing in Docker and EC2 environment.
